# Generated by Django 6.0.4 on 2026-04-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='card_image/'),
        ),
    ]
